title: Flavio's Blog
author: FlavioZamponi
email: flavio.zamponi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My awsome description. This is only some practising. Later maybe...

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
